### ISSUE TITLE
How to change the shape of the dots that generate the QR code

### ISSUE THREAD

**Issue by alanMachineLeraning** [heuer/segno#102]
How to change the shape of the dots that generate the QR code

**Comment by heuer** [comment]
This isn't possible and I guess it will never be supported by Segno natively because it would require 3rd party dependencies like PIL which I am trying to avoid. Segno itself should stay small and free of dependencies. 

Probably the plugin may support it in the future, see <https://github.com/heuer/qrcode-artistic/issues/6>

**Comment by alanMachineLeraning** [comment]
Thank you
