### ISSUE TITLE
vCard version 4 - support planed?

### ISSUE THREAD

**Issue by Fiebelkorn-mms** [heuer/segno#107]
Hello,

I only wanted to ask if there is a way to change the vCard version and if vCard version 4  support is planed?

**Comment by heuer** [comment]
Thank you for your idea. I don't think Segno will support vCard 4.0 any time soon.

In retrospect, I think that "segno.helpers" was a mistake, especially with regard to vCard and meCard.

vCard is so complex that I only wanted to achieve minimal coverage and stick to the general vCard 3.0 standard.

I view extensions to "segno.helpers" with some resentment, because I think that other libraries should do the job better and you should just feed Segno with the result (as a simple string).
