### ISSUE TITLE
Custom QR Codes with Logo

### ISSUE THREAD

**Issue by darryllane** [heuer/segno#116]
I have been looking at generating quite a few custom QR codes with email contact details and a logo in the centre. I cant seem to find any examples of this using Segno. Is this possible currently?

**Comment by heuer** [comment]
That's possible, but this project does not provide any helper function for this purpose since it requires more advanced image processing which is beyond the scope of this project.
However, Segno generates just simple PNG images which can be processed further.

Example code:

```python
import io
from PIL import Image
import segno

out = io.BytesIO()
# Nothing special here, let Segno generate the QR code and save it as PNG in a buffer
segno.make('Blackbird singing in the dead of night', error='h').save(out, scale=5, kind='png')
out.seek(0)  # Important to let Pillow load the PNG
img = Image.open(out)
# Ensure colors (Segno saves a grayscale PNG to reduce the file size), use 'RGBA' if you need transparency
img = img.convert('RGB')
img_width, img_height = img.size
logo_max_size = img_height // 3  # May use a fixed value as well
logo_img = Image.open('./blackbird.jpg')  # The logo
# Resize the logo to logo_max_size
logo_img.thumbnail((logo_max_size, logo_max_size), Image.Resampling.LANCZOS)
# Calculate the center of the QR code
box = ((img_width - logo_img.size[0]) // 2, (img_height - logo_img.size[1]) // 2)
img.paste(logo_img, box)
img.save('qrcode_with_logo.png')
```

QR Code:
![qrcode_without_logo](https://user-images.githubusercontent.com/364926/197056809-21c00c09-d737-48b6-af3c-2cc77bfaea96.png)

Logo:
![blackbird](https://user-images.githubusercontent.com/364926/197056823-2224b25a-6d81-44bf-9f4d-e617507afdcf.jpg)

Result:
![qrcode_with_logo](https://user-images.githubusercontent.com/364926/197056846-d0b8fb11-a26c-4114-9100-3d8521e556cf.png)

**Comment by heuer** [comment]
See also https://github.com/heuer/segno/tree/master/examples/logo

**Comment by darryllane** [comment]
Thanks I will have a tinker ^_^

**Comment by jdschwam** [comment]
How would I save the pasted image as a .svg?    ie img.save("qrcode.svg") 

Thanks

**Comment by heuer** [comment]
> How would I save the pasted image as a .svg? ie img.save("qrcode.svg")

That's unfortunately not possible. 
Maybe utilizing the CairoSVG lib https://cairosvg.org/documentation/ would help? But I don't have an example at hand.
