### ISSUE TITLE
Any plans to support currencies other than EUR?

### ISSUE THREAD

**Issue by Akif-Vohra** [heuer/segno#137]
This package is really useful. Thanks so much for this.

There are EU countries where SEPA can be used but the currency is different. Example Switzerland uses CHF. I see that documentation mentions only EUR is supported. Was that a permanent decision or is there a scope of making currency also configurable when using this package?

Thank you
Akif

**Comment by heuer** [comment]
Thanks for your kind words.

Acc. to my understanding the EPC only supports EUR since SEPA does not support any other currencies. 

"""[…] SEPA does not cover payments in currencies other than the euro. This means that domestic payments in SEPA countries not using the euro will continue to use local schemes, but cross-border payments will use SEPA and the euro with eurozone countries to a high degree. […]"""
Source: https://en.wikipedia.org/wiki/Single_Euro_Payments_Area
