### ISSUE TITLE
Add contact 'photo' field to vcards

### ISSUE THREAD

**Issue by ArthurReinhart** [heuer/segno#47]
I would be nice to add the photo field to the vcard

https://tools.ietf.org/html/rfc6350#section-6.2.4

   Examples:

       PHOTO:http://www.example.com/pub/photos/jqpublic.gif

       PHOTO:data:image/jpeg;base64,MIICajCCAdOgAwIBAgICBEUwDQYJKoZIhv
        AQEEBQAwdzELMAkGA1UEBhMCVVMxLDAqBgNVBAoTI05ldHNjYXBlIENvbW11bm
        ljYXRpb25zIENvcnBvcmF0aW9uMRwwGgYDVQQLExNJbmZvcm1hdGlvbiBTeXN0
        <...remainder of base64-encoded data...>

**Comment by heuer** [comment]
Thanks for your suggestion. 

IMO the ``helpers`` module is complicated enough. Creating a vCard required a lot of keywords. 
Further, binary data blows up the QR Code. 

Currently I think this shouldn't belong to Segno. Python provides a few libs which support vCard well. IMO it it would be better to use the libs and use the vCard output string as input for Segno to generate a QR Code. 

The ``helpers`` module is already almost beyond of the project's goal and was only added to generate some common things without the need to install a 2nd lib. 

See also #43 

What do you think?

**Comment by ArthurReinhart** [comment]
Helpers module may be just added as an extra, but is really useful, and i like using it isntead havind to install other libraries.

Maybe using an external library to generate the vCard is a good approach, but in my opinion this would be better as an option than a requirement.

**Comment by heuer** [comment]
Thanks for your explanation. 

I think having a photo URL may be possible but I am against an embedded image because the algorithm has to reach out to the URL, download the image, convert it into Base64 etc. IMO that's beyond the scope of the lib.

The output would be something like (taken from <https://tools.ietf.org/html/rfc2426#section-3.1.4> since the lib uses vCard 3.0)

`PHOTO;VALUE=uri:http://www.abc.com/pub/photos/jqpublic.gif`

Would it help?
